### PR TITLE
The finished source code

### PR DESCRIPTION
**Pull request by MrSn0wy**
hello!

This pr includes the last download page and some modifications to the rust updater script to download the artifacts.

To release this page on obliteration you will need to do the following:
1.  Make a `gh-pages` branch (this is where the actual website code is gonna go).
2. Download the source code from my [gh-pages](https://github.com/MrSn0wy/obhqWebsite/tree/gh-pages) branch.
3. Put it all into your `gh-pages` branch (and push it xS).
4. Then you can run the actions manually one time to confirm that it works.
5. From now on it should automatically update everything!

---

One small note, you should modify the following files of the screenshots for windows, linux and macos to the appropriate ones, basically just make 3 seperate images for each platform of the obliteration ui, preferably in dark mode.
```
public_html/download/_images/obliteration-windows-screenshot.png
public_html/download/_images/obliteration-linux-screenshot.png
public_html/download/_images/obliteration-macos-screenshot.png
```

### CODE REVIEW

**Comment by MrSn0wy** [comment]
Also i need to give you the secret token for the homebrew images. Is it possible that i can contact you outside of github ultima to provide you it?

**Comment by ultimaweapon** [comment]
> Also i need to give you the secret token for the homebrew images. Is it possible that i can contact you outside of github ultima to provide you it?

You can sent it via an email to ultimaweapon@outlook.com. Thanks!

**Review by ultimaweapon — APPROVED** [review]
I'll fix the Actions to publish the page later. Thanks for the PR!

**Comment by MrSn0wy** [comment]
> You can sent it via an email to [ultimaweapon@outlook.com](mailto:ultimaweapon@outlook.com). Thanks!

Hey Ultima! Did you ever receive the email? never got a response back

**Comment by ultimaweapon** [comment]
Yes I received it. Sorry for not letting you know.

**Pull request merged**
