### PR TITLE
The source code of the website

### PR DESCRIPTION
**Pull request by MrSn0wy**
Heya!
This is the current source code for the website.
This currently contains: the page that is currently on the domain, the home page, the compatibility page (still WIP), an update script for the database in rust (for the comp page), a php search script (also for the comp page), and the mdBook (for the wiki).

What do i still need to do? Finish the compatibility page and create the download page.

Also, a lot of the paths are incorrect and will be fixed once i am certain where we are gonna put the site (that seems to be github pages now?).

### CODE REVIEW

**Comment by SoffiMeower** [comment]
@ultimaweapon ^

**Comment by SoffiMeower** [comment]
Oh also, gonna need perms to point the Pages to the obliteration.net url.

**Comment by ultimaweapon** [comment]
Thanks for the PR. I might take a couple of days to review this due to my full time job. I'll try to finish the review as fast as possible.

**Comment by SoffiMeower** [comment]
@ultimaweapon Also, just wanna say... Sorry. Sure, we had our concerns, but I was overly being a jerk about it .w.
I think I was mainly worried that we'd have to completely redo the website to make it work with Github Pages but... Well, let's just say that slluxx, the person who stumbled upon our argument... Actually helped describe how we could make it work with Github Actions.

**Review by ultimaweapon — APPROVED** [review]
I don't feel confident to make this go live for now due to it seems like there are some XSS vulnerabilities. We probably need to move to a JS framework so we don't need to worry about this. I'll approve this for now so we can fix the issue one by one later.

**Comment by MrSn0wy** [comment]
Yeah still gotta add csp for xss, but because its still in development i haven't done that yet. I don't think a js framework is gonna be needed, i can just add csp to the html.

**Pull request merged**
